normal = {
"%20":" ",
"%26":"&",
"%\2C":",",
"%\2c":",",
"%28":"(",
"%29":")",
"%21":"!",
"%\3D":"=",
"%\3d":"=",
"%\3C":"<",
"%\3c":"<",
"%\3E":">",
"%\3e":">",
"%23":"#",
"%24":" dollars ",
"%27":"'",
"%\2A":"*",
"%\2D":"-",
"%\2d":"-",
"%\2E":".",
"%\2e":".",
"%\2F":"/",
"%\2f":"/",
"%\3A":":",
"%\3a":":",
"%\3B":";",
"%\3b":";",
"%\3F":"?",
"%\3f":"?",
"%40":"@",
"%\5B":"[",
"%\5b":"[",
# "%\5C":"\\",
# "%\5c":"\\",
"%\5D":"]",
"%\5d":"]",
"%\5F":"_",
"%\5f":"_",
"%60":"`",
"%\7B":"{",
"%\7b":"{",
"%\7C":"|",
"%\7c":"|",
"%\7D":"}",
"%\7d":"}",
# "%22":""",
"%27":"'",
"%\3F":"?",
"%\3f":"?",
"+":" plus ",
"%":" percent ",
".com":" dot com ",
".org":" dot org ",
".edu":" dot edu ",
".gov":" dot gov ",
".uk":" dot uk ",
".net":" dot net ",
".ca":" dot ca ",
".de":" dot de ",
".jp":" dot jp ",
".fr":" dot fr ",
".au":" dot au ",
".us":" dot us ",
".ru":" dot ru ",
".ch":" dot ch ",
".it":" dot it ",
".nl":" dot nl ",
".se":" dot se ",
".no":" dot no ",
".es":" dot es ",
".mil":" dot mil ",
".co":" dot co ",
" a.l.i.c.e ":" ALICE ",
" a.l.i.c.e. ":" ALICE ",
" a.":" A ",
" ain t ":" is not ",
" ain't ":" is not ",
" alicebot ":" alice ",
" aman ":" am an ",
" amfine ":" am fine ",
" amleaving ":" am leaving ",
" amnot ":" am not ",
" amon ":" am on ",
" apr. ":" Apr ",
" aren t ":" are not ",
" aren.t ":" are not ",
" arent ":" are not ",
" aren't ":" are not ",
" are'nt ":" are not ",
" arn t ":" are not ",
" aug. ":" Aug ",
" b.":" B ",
" becasue ":" because ",
" becouse ":" because ",
" becuase ":" because ",
" becuse ":" because ",
" beleive ":" believe ",
" botspot.":" botspot dot ",
" c.":" C ",
" can t ":" can not ",
" can.t ":" can not ",
" cannot ":" can not ",
" cant ":" can not ",
" can't ":" can not ",
" colour ":" color ",
" couldn t ":" could not ",
" couldn.t ":" could not ",
" couldn't ":" could not ",
" could've ":" could have ",
" d.":" D ",
" dec. ":" Dec ",
" didn t ":" did not ",
" didnt ":" did not ",
" didn't ":" did not ",
" did'nt ":" did not ",
" do nt ":" do not ",
" doesn t ":" does not ",
" doesn.t ":" does not ",
" doesnt ":" does not ",
" doesn't ":" does not ",
" don t ":" do not ",
" don.t ":" do not ",
" dont ":" do not ",
" don't ":" do not ",
" do'nt ":" do not ",
" down load ":" download ",
" dr . ":" Doctor ",
" dr. ":" Doctor ",
" sr . ":" Doctor ",
" sr. ":" Senior ",
" jr. ":" Junior ",
" e l v i s ":" elvis ",
" e.":" E ",
" e.l.v.i.s ":" elvis ",
" e.l.v.i.s. ":" elvis ",
" 'em ":" them ",
" etc. ":" etc ",
" everything's ":" everything is ",
" f.":" F ",
" fav ":" favorite ",
" favourite ":" favorite ",
" feb. ":" Feb ",
" fri. ":" Fri ",
" g.":" G ",
" h.":" H ",
" h.a.l. ":" hal ",
" hadn t ":" had not ",
" hadn.t ":" had not ",
" hadn't ":" had not ",
" haha":" ha",
" hasn t ":" has not ",
" hasn't ":" has not ",
" havent ":" have not ",
" haven't ":" have not ",
" he d ":" he would ",
" he ll ":" he will ",
" he s ":" he is ",
" he.ll ":" he will ",
" he.s ":" he is ",
" hed ":" he would ",
" he'd ":" he would ",
" hehe":" he",
" he'll ":" he will ",
" hellp ":" help ",
" he's ":" he is ",
" how d ":" how did ",
" how s ":" how is ",
" how'd ":" how did ",
" how'd ":" how would ",
" hows ":" how is ",
" how's ":" how is ",
" i m ":" I am ",
" i ve ":" I have ",
" i.":" I ",
" i.c.e ":" i c e ",
" i.d ":" I would ",
" i.ll ":" I will ",
" i.m ":" I am ",
" i.ve ":" I have ",
" iam ":" I am ",
" iama ":" I am a ",
" iamasking ":" I am asking ",
" iamdoing ":" I am doing ",
" iamfrom ":" I am from ",
" iamin ":" I am in ",
" iamok ":" I am ok ",
" iamsorry ":" I am sorry ",
" iamtalking ":" I am talking ",
" iamtired ":" I am tired ",
" iamusing ":" I am using ",
" i'd ":" I would ",
" i'll ":" I will ",
" i'm ":" I am ",
" inc. ":" Inc ",
" isn t ":" is not ",
" isn.t ":" is not ",
" isnt ":" is not ",
" isn't ":" is not ",
" it s ":" it is ",
" it.ll ":" it will ",
" it.s ":" it is ",
" it'd ":" it would ",
" it'll ":" it will ",
" it's ":" it is ",
" its a ":" it is a ",
" ive ":" I have ",
" i've ":" I have ",
" j.":" J ",
" jan. ":" Jan ",
" jul. ":" Jul ",
" jun. ":" Jun ",
" k.":" K ",
" l.":" L ",
" l.l. ":" L L ",
" let s ":" let us ",
" let.s ":" let us ",
" let's ":" let us ",
" loebner price ":" loebner prize ",
" m.":" M ",
" mar. ":" Mar ",
" may. ":" May ",
" might've ":" might have ",
" mon. ":" Mon ",
" mr. ":" mr ",
" mr.":" mr ",
" mrs. ":" mrs ",
" ms.":" ms ",
" n.":" n ",
" name's ":" name is ",
" noi ":" yes i ",
" nov. ":" Nov ",
" o k ":" OK ",
" o. k. ":" OK ",
" o.":" o ",
" o.k. ":" ok ",
" oct. ":" Oct ",
" ohh ":" oh ",
" p s ":" ps ",
" p.":" P ",
" p.s. ":" ps ",
" ph.d. ":" phd ",
" practice ":" practise ",
" q.":" Q ",
" r.":" R ",
" realy ":" really ",
" reductionalism ":" reductionism ",
" remeber ":" remember ",
" s.":" S ",
" sat. ":" Sat ",
" sep. ":" Sep ",
" sept. ":" Sept ",
" she d ":" she would ",
" she s ":" she is ",
" she.ll ":" she will ",
" she.s ":" she is ",
" shed ":" she would ",
" she'd ":" she would ",
" she'll ":" she will ",
" shes ":" she is ",
" she's ":" she is ",
" shouldn.t ":" should not ",
" shouldnt ":" should not ",
" shouldn't ":" should not ",
" sr.":" sr ",
" st. ":" st ",
" st.":" st ",
" sun. ":" sun ",
" t.":" T ",
" that ll ":" that will ",
" that s ":" that is ",
" that.s ":" that is ",
" that'd ":" that did ",
" that'll ":" that will ",
" thats ":" that is ",
" that's ":" that is ",
" there s ":" there is ",
" there.s ":" there is ",
" there'll ":" there will ",
" theres ":" there is ",
" there's ":" there is ",
" they re ":" they are ",
" they.ll ":" they will ",
" they.re ":" they are ",
" they'd ":" they would ",
" they'll ":" they will ",
" they're ":" they are ",
" they've ":" they have ",
" this'll ":" this will ",
" thu. ":" Thu ",
" 'tis ":" it is ",
" tue. ":" Tue ",
" u s a ":" USA ",
" u. s. a. ":" USA ",
" u.":" u ",
" u.s. ":" USA ",
" u.s.a. ":" USA ",
" ur ":" your ",
" v.":" v ",
" v.i.s ":" v i s ",
" w.":" w ",
" waht ":" what ",
" wanna ":" want to ",
" wasn t ":" was not ",
" wasnt ":" was not ",
" wasn't ":" was not ",
" we ll ":" we will ",
" we re ":" we are ",
" we ve ":" we have ",
" we.d ":" we would ",
" we.ll ":" we will ",
" we.re ":" we are ",
" we.ve ":" we have ",
" we'd ":" we would ",
" wed. ":" wed ",
" we'll ":" we will ",
" welli ":" well i ",
" wellit ":" well it ",
" we're ":" we are ",
" weren t ":" were not ",
" weren.t ":" were not ",
" werent ":" were not ",
" weren't ":" were not ",
" we've ":" we have ",
" what s ":" what is ",
" what.s ":" what is ",
" what'd ":" what did ",
" whatis.":" whatis dot ",
" what'll ":" what will ",
" whats ":" what is ",
" what's ":" what is ",
" where s ":" where is ",
" where.s ":" where is ",
" where's ":" where is ",
" who s ":" who is ",
" who.s ":" who is ",
" whos ":" who is ",
" who's ":" who is ",
" why.s ":" why is ",
" why's ":" why is ",
" won t ":" will not ",
" won.t ":" will not ",
" wont ":" will not ",
" won't ":" will not ",
" wouldn t ":" would not ",
" wouldn.t ":" would not ",
" wouldnt ":" would not ",
" wouldn't ":" would not ",
" would've ":" would have ",
" www. ":"www dot ",
" www.":" www dot ",
" x.":" x ",
" y.":" y ",
" yesi ":" yes i ",
" yesit ":" yes it ",
" yha ":" yes ",
" you ll ":" you will ",
" you r ":" you are ",
" you re ":" you are ",
" you ve ":" you have ",
" you.d ":" you had ",
" you.ll ":" you will ",
" you.re ":" you are ",
" you.ve ":" you have ",
" you'd ":" you had ",
" you'd ":" you would ",
" you'll ":" you will ",
" youre ":" you are ",
" you're ":" you are ",
" you've ":" you have ",
" yuo ":" you ",
" z.":" z ",
"http://":" http colon slash slash ",
"'":" ",
"-":" dash ",
"#":" sharp ",
"$":" dollarsign ",
"&":" ",
"(":" lparen ",
")":" rparen ",
"*":" star ",
":":" ",
": and ":".  ",
": but ":".  ",
": do ":".  do ",
": i ":".  i ",
": what ":".  what ",
": you ":".  you ",
":)":" smile ",
":and ":".  ",
":but ":".  ",
":do ":".  do ",
":i ":".  i ",
":what ":".  what ",
":you ":".  you ",
"...":".",
".0":" point 0",
".1":" point 1",
".2":" point 2",
".3":" point 3",
".4":" point 4",
".5":" point 5",
".6":" point 6",
".7":" point 7",
".8":" point 8",
".9":" point 9",
".ac ":" dot ac ",
".au ":" dot au ",
".co ":" dot co ",
".com ":" dot com ",
".edu ":" dot edu ",
".jar":" jar",
".jp ":" dot jp ",
".net ":" dot net ",
".org ":" dot org ",
".uk ":" dot uk ",
".zip":" zip",
"/":" slash ",
": 0":" 0",
": 1":" 1",
": 2":" 2",
": 3":" 3",
": 4":" 4",
": 5":" 5",
":":" ",
":-(":" frown ",
":-)":" smile ",
":)":" smile ",
":-)":" smile ",
":0":" colon 0",
":1":" colon 1",
":2":" colon 2",
":3":" colon 3",
":4":" colon 4",
":5":" colon 5",
":6":" colon 6",
":7":" colon 7",
":8":" colon 8",
":9":" colon 9",
";":" ",
";)":" smile ",
";-)":" smile ",
"@":" at ",
"[":" leftbracket ",
"]":" rightbracket ",
"^":" uparrow ",
"_":" underscore ",
"`":" ",
"{":" beginscript ",
"{":" leftcurly ",
"}":" endscript ",
"}":" rightcurly ",
"<":" lt ",
"<3":" heart ",
"=":" equals ",
">":" gt ",
"'s":" s",
"ku ":" aku ",
" saya ":" aku ",
" gue ":" aku ",
" gua ":" aku ",
" gw ":" aku ",
"mu ":" kamu ",
" anda ":" kamu ",
" loe ":" kamu ",
" lo ":" kamu ",
" lu ":"mu ",
" elo ":" kamu ",
" lau ":" kamu ",
" ia ":" dia ",
" dia laki-laki ":" dia ",
" dia perempuan ":" dia ",
" kta ":" kita ",
" qta ":" kita ",
" kmi ":" kami ",
" mrk ":" mereka ",
" mrka ":" mereka ",
" dia orang ":" mereka ",
" jender ":" jenis kelamin ",
" jnis klmin ":" jenis kelamin ",
" jns klmn ":" jenis kelamin ",
" laki laki ":" laki-laki ",
" lakilaki ":" laki-laki ",
" laki2 ":" laki-laki ",
" lk2 ":" laki-laki ",
" pr ":" perempuan ",
" prmpn ":" perempuan ",
" prmpuan ":" perempuan ",
" wanita ":" perempuan ",
" wnta ":" perempuan ",
" mama ":" ibu ",
" mamah ":" ibu ",
" mm ":" ibu ",
" bunda ":" ibu ",
" mami ":" ibu ",
" umi ":" ibu ",
" papa ":" ayah ",
" papah ":" ayah ",
" pp ":" ayah ",
" papi ":" ayah ",
" abi ":" ayah ",
" eyang ":" nenek ",
" yangti ":" nenek ",
" mbah puteri ":" nenek ",
" oma ":" nenek ",
" nnk ":" nenek ",
" mbah kakung ":" kakek ",
" opa ":" kakek ",
" kkek ":" kakek ",
" anak perempuan ":" puteri ",
" putri ":" puteri ",
" anak laki-laki ":" putera ",
" putra ":" putera ",
" Jan ":" Januari ",
" Feb ":" Februari ",
" Mar ":" Maret ",
" Mrt ":" Maret ",
" Apr ":" April ",
" Aprl ":" April ",
" Mey ":" Mei ",
" Jun ":" Juni ",
" Jul ":" Juli ",
" Agsts ":" Agustus ",
" Agust ":" Agustus ",
" Sep ":" September ",
" Sept ":" September ",
" Sptmbr ":" September ",
" Okt ":" Oktober ",
" Oktbr ":" Oktober ",
" Nov ":" November ",
" Nopember ":" November ",
" Nop ":" November ",
" Des ":" Desember ",
" Dsmbr ":" Desember ",
" hr ":" hari ",
" hr2 ":" hari-hari ",
" hari2 ":" hari-hari ",
" bsk ":" besok ",
" thn ":" tahun ",
" bln ":" bulan ",
" wkt ":" waktu ",
" wktu ":" waktu ",
" tgl ":" tanggal ",
" tggl ":" tanggal ",
" pgi ":" pagi ",
" sre ":" sore ",
" bgmn ":" bagaimana ",
" bgmna ":" bagaimana ",
" gimana ":" bagaimana ",
" gmn ":" bagaimana ",
" gmna ":" bagaimana ",
" spa ":" siapa ",
" syapa ":" siapa ",
" brp ":" berapa ",
" brpa ":" berapa ",
" dmn ":" dimana ",
" di mana ":" dimana ",
" ap ":" apa ",
" apkh ":" apakah ",
" kpn ":" kapan ",
" kpan ":" kapan ",
" prov ":" provinsi ",
" prov. ":" provinsi ",
" kab ":" kabupaten ",
" kab. ":" kabupaten ",
" kel ":" kelurahan ",
" kel. ":" kelurahan ",
" kec ":" kecamatan ",
" kec. ":" kecamatan ",
" ijo ":" hijau ",
" hejo ":" hijau ",
" binatang ":" hewan ",
" almt ":" alamat ",
" almat ":" alamat ",
" t4 ":" tempat ",
" tmpt ":" tempat ",
" tmpat ":" tempat ",
" lhr ":" lahir ",
" lhir ":" lahir ",
" imel ":" email ",
" pilm ":" film ",
" pelm ":" film ",
" mkn ":" makan ",
" maem ":" makan ",
" olah raga ":" olahraga ",
" eskrim ":" es krim ",
" es kream ":" es krim ",
" mnm ":" minum ",
" mimik ":" minum ",
" faforit ":" favorit ",
" fav ":" favorit ",
" paforit ":" favorit ",
" ska ":" suka ",
" bahagia ":" senang ",
" gembira ":" senang ",
" seneng":" senang ",
" mlk ":" milik ",
" punya ":" milik ",
" pnya ":" milik ",
" dr ":" dokter ",
" dr. ":" dokter ",
" pengen ":" ingin ",
" pingin ":" ingin ",
" mau ":" ingin ",
" tau ":" tahu ",
" baek ":" baik ",
" bae ":" baik ",
" paling ":" sangat ",
" sngt ":" sangat ",
" tntg ":" tentang ",
" mengenai ":" tentang ",
" bnyk ":" banyak ",
" bnyak ":" banyak ",
" yg ":" yang ",
" yng ":" yang ",
" ap ":" apa ",
" apkh ":" apakah ",
" akn ":" akan ",
" lbh ":" lebih ",
" jg ":" juga ",
" jga ":" juga ",
" uga ":" juga ",
" dri ":" dari ",
" tinggl ":" tinggal ",
" skrg ":" sekarang ",
" skrng ":" sekarang ",
" saat ini ":" sekarang ",
" sklh ":" sekolah ",
" sdh ":" sudah ",
" udah ":" sudah ",
" telah ":" sudah ",
" tlah ":" sudah ",
" nkh ":" nikah ",
" stu ":" satu ",
" atu ":" satu ",
" slah ":" salah ",
" slh ":" salah ",
" lma ":" lama ",
" lm ":" lama ",
" dpt ":" dapat ",
" dpet ":" dapat ",
" tmbah ":" tambah ",
" nambah ":" tambah ",
" nmbah ":" tambah ",
" knal ":" kenal ",
" usia ":" umur ",
" tdak ":" tidak ",
" tdk ":" tidak ",
" ndak ":" tidak ",
" adlah ":" adalah ",
" adlh ":" adalah ",
" kasih ":" beri ",
" ksh ":" beri ",
" ksih ":" beri ",
" terimakasih ":" terima kasih ",
" trmksh ":" terima kasih ",
" trmksih ":" terima kasih ",
" trims ":" terima kasih ",
" trim ":" terima kasih ",
" belom ":" belum ",
" blm ":" belum ",
" blum ":" belum ",
" blom ":" belum ",
" lngkap ":" lengkap ",
" lngkp ":" lengkap ",
" dpan ":" depan ",
" dpn ":" depan ",
" blkng ":" belakang ",
" blkang ":" belakang ",
" disini ":" di sini ",
" ngomong ":" bicara ",
" ngmng ":" bicara ",
" ngmong ":" bicara ",
" orang2 ":" orang-orang ",
" org2 ":" orang-orang ",
" orng2 ":" orang-orang ",
" telpon ":" telepon ",
" telp ":" orang-orang ",
" bgus ":" bagus ",
" bgs ":" bagus ",
" televisi ":" TV ",
" televisi ":" TV ",
" fikir ":" pikir ",
" cntik ":" cantik ",
" cntk ":" cantik ",
" lksi ":" lokasi ",
" plhra ":" pelihara ",
" plihara ":" pelihara ",
" njing ":" anjing ",
" guguk ":" anjing ",
" kcing ":" kucing ",
" tngh ":" tengah ",
" tngah ":" tengah ",
" klrga ":" keluarga ",
" klrg ":" keluarga ",
" ulangtahun ":" ulang tahun ",
" ultah ":" ulang tahun ",
" ulngthn ":" ulang tahun ",
" inget ":" ingat ",
" ingt ":" ingat ",
" denger ":" dengar ",
" cri ":" cari ",
" akrap ":" akrab ",
" akrb ":" akrab ",
" akrp ":" akrab ",
" hei ":" hai ",
" lhat ":" lihat ",
" lht ":" lihat ",
" ok ":" oke ",
" okey ":" oke ",
" okay ":" oke ",
" kpda ":" kepada ",
" kpd ":" kepada ",
" ubh ":" ubah ",
" tmpil ":" tampil ",
" misua ":" suami ",
" propil ":" profil ",
" nomer ":" nomor ",
" no ":" nomor ",
" no. ":" nomor ",
" nmr ":" nomor ",
" pntng ":" penting ",
" pnting ":" penting ",
" untk ":" untuk ",
" u/ ":" untuk ",
" smpai ":" sampai ",
" stlah ":" setelah ",
" stlh ":" setelah ",
}